Proyecto2/App1/urls.py
from django.urls import path
from App1 import views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView


urlpatterns = [
   
    path('', views.inicio, name="Inicio"), #este era nuestro primer view
    path('gasto', login_required(views.gasto), name="Gasto"), # comando que requiere login para acceder a esta clase
    #path('gasto', views.gasto, name="Gasto"),
    path('ingreso', login_required(views.ingreso), name="Ingreso"), # comando que requiere login para acceder a esta clase
    #path('ingreso', views.ingreso, name="Ingreso"),
    path('trading', login_required(views.trading), name="Trading"), # comando que requiere login para acceder a esta clase
    #path('trading', views.trading, name="Trading"),

    path('gastoFormulario', views.gastoFormulario, name="GastoFormulario"),
    path('ingresoFormulario', views.ingresoFormulario, name="IngresoFormulario"),
    path('tradingFormulario', views.tradingFormulario, name="TradingFormulario"),
    
    path('busquedaGasto',views.busquedaGasto,name="BusquedaGasto"),
    path('buscarGasto/',views.buscarGasto),
    path('busquedaIngreso',views.busquedaIngreso,name="BusquedaIngreso"),
    path('buscarIngreso/',views.buscarIngreso),
    path('busquedaTrading',views.busquedaTrading,name="BusquedaTrading"), 
    path('buscar/',views.buscar),
    

    path('leerGastos',views.leerGastos,name='LeerGastos'),
    path('leerIngresos',views.leerIngresos,name='LeerIngresos'),
    path('leerTradings',views.leerTradings,name='LeerTradings'),

    path('eliminarGasto/<gasto_fecha>/', views.eliminarGasto, name="EliminarGasto"),
    path('eliminarIngreso/<ingreso_fecha>/', views.eliminarIngreso, name="EliminarIngreso"),
    path('eliminarTrading/<trading_fecha>/', views.eliminarTrading, name="EliminarTrading"),

    path('editarGasto/<gasto_fecha>/', views.editarGasto, name="EditarGasto"),
    path('editarIngreso/<ingreso_fecha>/', views.editarIngreso, name="EditarIngreso"),
    path('editarTrading/<trading_fecha>/', views.editarTrading, name="EditarTrading"),

    #path('gasto/list',views.GastoList.as_view(),name='List'),
    #path(r'^(?P<pk>\d+)$', views.GastoDetalle.as_view(),name='Detail'),
    #path(r'^nuevo$', views.GastoCreacion.as_view(),name='New'),
    #path(r'^editar/(?P<pk>\d+)$',views.GastoUpdate.as_view(),name='Edit'),
    #path(r'^borrar/(?P<pk>\d+)$',views.GastoDelete.as_view(),name='Delete'),

    #path('ingreso/list',views.IngresoList.as_view(),name='List'),
    #path(r'^(?P<pk>\d+)$', views.IngresoDetalle.as_view(),name='Detail'),
    #path(r'^nuevo$', views.IngresoCreacion.as_view(),name='New'),
    #path(r'^editar/(?P<pk>\d+)$',views.IngresoUpdate.as_view(),name='Edit'),
    #path(r'^borrar/(?P<pk>\d+)$',views.IngresoDelete.as_view(),name='Delete'),

    path('trading/list',views.TradingList.as_view(),name='List'),
    path(r'^(?P<pk>\d+)$', views.TradingDetalle.as_view(),name='Detail'),
    path(r'^nuevo$', views.TradingCreacion.as_view(),name='New'),
    path(r'^editar/(?P<pk>\d+)$',views.TradingUpdate.as_view(),name='Edit'),
    path(r'^borrar/(?P<pk>\d+)$',views.TradingDelete.as_view(),name='Delete'),

    path('login',views.login_request, name="Login"),
    path('register', views.register, name='Register'),
    path('logout', LogoutView.as_view(template_name='App1/logout.html'), name='Logout'),

    path("my-page/", views.MyView.as_view(), name="my_page"),
    path("my-protected-page/", views.MyProtectedView.as_view(), name="my_protected_page"),

    path('editarPerfil', views.editarPerfil, name="EditarPerfil"),
    
    path('agregarAvatar', views.agregarAvatar, name="AgregarAvatar"),
    path('aboutMe', views.aboutMe, name="AboutMe"),
    path('noEnviastesNada', views.noEnviastesNada, name="NoEnviastesNada"),

        

]

Proyecto2/Proyecto2/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('App1/',include('App1.urls'))
]

from django.conf import settings
from django.conf.urls.static import static
urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Proyecto2/App1/models.py
from django.db import models

# en el minuto 01:20:16 de la clase 18 esplica como cambiar el tipo de imformacion a recibir en los datos de entratada i.e int, str etc
# Create your models here.
class Gasto(models.Model):
    fecha= models.DateField()
    renta= models.IntegerField()
    alimentacion= models.IntegerField()
    educacion= models.IntegerField()
    transporte= models.IntegerField()    
    bills= models.IntegerField()
    vestuario= models.IntegerField()
    recreacion= models.IntegerField()  
    otros= models.IntegerField()
    def __str__(self):
        return f"Fecha: {self.fecha} - Renta {self.renta} - Alimentacion {self.alimentacion} - Educacion {self.educacion}  - Transporte {self.transporte}  - Bills {self.bills}  - Vestuario {self.vestuario}  - Recreacion {self.recreacion}  - Otros {self.otros}"
class Ingreso(models.Model):
    fecha= models.DateField()
    salario= models.IntegerField()
    part_time= models.IntegerField()
    alquileres= models.IntegerField()    
    otros= models.IntegerField()  
    def __str__(self):
        return f"Fecha: {self.fecha} - Salario {self.salario} - Part_Time {self.part_time} - Alquileres {self.alquileres}  - Otros {self.otros}"  
class Trading(models.Model):
    fecha= models.DateField()
    cryptocurrency= models.IntegerField()
    acciones= models.IntegerField()
    otros= models.IntegerField()
    def __str__(self):
        return f"Fecha: {self.fecha} - Cryptocurrency {self.cryptocurrency} - Acciones {self.acciones} - Otros {self.otros}"
    

from django.contrib.auth.models import User
# Clase 24
class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatares', null=True, blank = True)
    def __str__(self):
        return f"{self.user} - {self.imagen}"
    

'''
# Chequear si todo esta correcto
-->python manage.py check App1 
Deberia salirte: System check identified no issues (0 silenced).

# Transformar modelos a bases de datos
-->python manage.py makemigrations

# Ya se tiene la BD pero hay que alimentarla
-->python manage.py sqlmigrate App1 0001
# 0001 es el numero de la migracion se necesita un formato de 4 digitos
# Tambien podrias hacer: python manage.py sqlmigrate App1 initial
# Esto te devolvera todas las sql para crear las tablas

# Hacer la migracion 
-->python manage.py migrate

# Vamos al terminal y hacemos esto:
-->python manage.py createsuperuser
# Ingresa usernmae, email adress y password dos veces
luego corremos el codigo para probarlo
-->python manage.py runserver
'''

Proyecto2/App1/views.py
from django.shortcuts import render
from App1.models import *  #Gasto, Ingreso, Trading, Avatar
from django.http import HttpResponse
from App1.forms import * #GastoFormulario, IngresoFormulario, TradingFormulario


from django.contrib.auth.decorators import login_required

# Create your views here.
def inicio(request):
    return render(request, 'App1/inicio.html')
@login_required # comnado que requiere login para acceder a esta clase
def gasto(request):
    return render(request,'App1/gastos.html')
@login_required # comnado que requiere login para acceder a esta clase
def ingreso(request):
    return render(request,'App1/ingresos.html')
@login_required # comnado que requiere login para acceder a esta clase
def trading(request):
    return render(request,'App1/tradings.html')
def login(request):
    return render(request,'App1/login.html')
def logout(request):
    return render(request,'App1/logout.html')
def register(request):
    return render(request,'App1/registro.html')
def editarPerfil(request):
    return render(request,'App1/editarPerfil.html')
@login_required # comnado que requiere login para acceder a esta clase
def aboutMe(request):
    return render(request,'App1/aboutMe.html')
def noEnviastesNada(request):
    return render(request,'App1/noEnviastesNada.html')


###gastos POST
def gasto(request):  ######depronto agregar eses ssss a estas funciones
    if request.method =='POST':
        miFormulario=GastoFormulario(request.POST)
        print(miFormulario)

        if miFormulario.is_valid:
            informacion=miFormulario.cleaned_data
            gasto=Gasto(int(informacion['id']),str(informacion['fecha']),int(informacion['renta']),
                        int(informacion['alimentacion']),int(informacion['educacion']),
                        int(informacion['transporte']),int(informacion['bills']),
                        int(informacion['vestuario']),int(informacion['recreacion']),
                        int(informacion['otros']))
            gasto.save()
            return render(request, 'App1/inicio.html')
    else:
        miFormulario=GastoFormulario()
    return render(request, 'App1/gastos.html', {"miFormulario": miFormulario})

###ingreso POST
def ingreso(request):
    if request.method =='POST':
        miFormulario=IngresoFormulario(request.POST)
        print(miFormulario)

        if miFormulario.is_valid:
            informacion=miFormulario.cleaned_data
            ingreso=Ingreso(int(informacion['id']),str(informacion['fecha']),int(informacion['salario']),
                            int(informacion['part_time']),int(informacion['alquileres']),
                            int(informacion['otros']))
            ingreso.save()
            return render(request, 'App1/inicio.html')
    else:
        miFormulario=IngresoFormulario()
    return render(request, 'App1/ingresos.html', {"miFormulario": miFormulario})

###trading POST
def trading(request):
    if request.method =='POST':
        miFormulario=TradingFormulario(request.POST)
        print(miFormulario)

        if miFormulario.is_valid:
            informacion=miFormulario.cleaned_data
            trading=Trading(int(informacion['id']),str(informacion['fecha']),
                            int(informacion['cryptocurrency']),int(informacion['acciones']),
                            int(informacion['otros']))
            trading.save()
            return render(request, 'App1/inicio.html')
    else:
        miFormulario=TradingFormulario()
    return render(request, 'App1/tradings.html', {"miFormulario": miFormulario})

###formularios para enviar informacion
def gastoFormulario(request):
     if request.method == "POST":
        miFormulario = GastoFormulario(request.POST) # Aqui me llega la informacion del html
        print(miFormulario)
        
        if miFormulario.is_valid:
            informacion = miFormulario.cleaned_data
            gasto = Gasto(int(informacion['id']),str(informacion['fecha']),
                              int(informacion['renta']),int(informacion['alimentacion']), 
                              int(informacion['educacion']),int(informacion['transporte']),
                              int(informacion['bills']),int(informacion['vestuario']),
                              int(informacion['recreacion']),int(informacion['otros']))
            gasto.save()
            return render(request, "App1/inicio.html")
     else:
        miFormulario = GastoFormulario()
             
     return render(request, "App1/gastoFormulario.html", {"miFormulario": miFormulario})
###formularios para enviar informacion
def ingresoFormulario(request):
     if request.method == "POST":
        miFormulario = IngresoFormulario(request.POST) # Aqui me llega la informacion del html
        print(miFormulario)
        
        if miFormulario.is_valid:
            informacion = miFormulario.cleaned_data
            ingreso = Ingreso(int(informacion['id']),str(informacion['fecha']),
                              int(informacion['salario']),int(informacion['part_time']), 
                              int(informacion['alquileres']),int(informacion['otros']))
            ingreso.save()
            return render(request, "App1/inicio.html")
     else:
        miFormulario = IngresoFormulario()
             
     return render(request, "App1/ingresoFormulario.html", {"miFormulario": miFormulario})
###formularios para enviar informacion
def tradingFormulario(request):
     if request.method == "POST":
        miFormulario = TradingFormulario(request.POST) # Aqui me llega la informacion del html
        print(miFormulario)
        
        if miFormulario.is_valid:
            informacion = miFormulario.cleaned_data
            trading = Trading(int(informacion['id']),str(informacion['fecha']),
                              int(informacion['cryptocurrency']),int(informacion['acciones']), 
                              int(informacion['otros']))
            trading.save()
            return render(request, "App1/inicio.html")
     else:
        miFormulario = TradingFormulario()
             
     return render(request, "App1/tradingFormulario.html", {"miFormulario": miFormulario})


###busqueda GASTO REQUEST
@login_required # comnado que requiere login para acceder a esta clase
def busquedaGasto(request):
     return render(request,'App1/busquedaGasto.html')

def buscarGasto(request): #la funcion buscar de cada clase se llama diferente 
     if request.GET['fecha']:
          fecha = request.GET['fecha']
          fechas= Gasto.objects.filter(fecha__icontains=fecha)

          return render(request,'App1/busquedaGasto.html', {"fechas":fechas, "comisiones": fechas })
     else:
          return render(request,'App1/noEnviastesNada.html')

###busqueda Ingreso REQUEST
@login_required # comnado que requiere login para acceder a esta clase
def busquedaIngreso(request):
     return render(request,'App1/busquedaIngreso.html')

def buscarIngreso(request): #la funcion buscar de cada clase se llama diferente 
     if request.GET['fecha']:
          fecha = request.GET['fecha']
          fechas= Ingreso.objects.filter(fecha__icontains=fecha)

          return render(request,'App1/busquedaIngreso.html', {"fechas":fechas, "comisiones": fechas })
     else:
          return render(request,'App1/noEnviastesNada.html')

###busqueda trading REQUEST
@login_required # comnado que requiere login para acceder a esta clase
def busquedaTrading(request):
     return render(request,'App1/busquedaTrading.html')

def buscar(request): #la funcion buscar de cada clase se llama diferente 
     if request.GET['fecha']:
          fecha = request.GET['fecha']
          fechas= Trading.objects.filter(fecha__icontains=fecha)

          return render(request,'App1/busquedaTrading.html', {"fechas":fechas, "comisiones": fechas })
     else:
          return render(request,'App1/noEnviastesNada.html')


###leer, funciones para visualizar toda la informacion de los objetos creados
@login_required # comnado que requiere login para acceder a esta clase
def leerGastos(request):
    gastos= Gasto.objects.all() # trae a todos los gastos
    contexto= {"gastos": gastos}
    return render(request, "App1/leerGastos.html",contexto)
@login_required # comnado que requiere login para acceder a esta clase
def leerIngresos(request):
    ingresos= Ingreso.objects.all() # trae a todos los ingresos
    contexto= {"ingresos": ingresos}
    return render(request, "App1/leerIngresos.html",contexto)
@login_required # comnado que requiere login para acceder a esta clase
def leerTradings(request):
    tradings= Trading.objects.all() # trae a todos los tradings
    contexto= {"tradings": tradings}
    return render(request, "App1/leerTradings.html",contexto)

###delete, funciones para borrar objetos
def eliminarGasto(request, gasto_fecha):
    gasto = Gasto.objects.get(fecha=gasto_fecha)
    gasto.delete()
    # vuelvo al menú
    gastos = Gasto.objects.all()  # trae todos los gastos 
    contexto = {"gastos": gastos}
    return render(request, "App1/leerGastos.html", contexto)

def eliminarIngreso(request, ingreso_fecha):
    ingreso = Ingreso.objects.get(fecha=ingreso_fecha)
    ingreso.delete()
    # vuelvo al menú
    ingresos = Ingreso.objects.all()  # trae todos los ingresos
    contexto = {"ingresos": ingresos}
    return render(request, "App1/leerIngresos.html", contexto)

def eliminarTrading(request, trading_fecha):
    trading = Trading.objects.get(fecha=trading_fecha)
    trading.delete()
    # vuelvo al menú
    tradings = Trading.objects.all()  # trae todos los tradings
    contexto = {"tradings": tradings}
    return render(request, "App1/leerTradings.html", contexto)

###update funciones para actualizar objetos de la clase Gastos
def editarGasto(request, gasto_fecha):
    # Recibe la fecha de gasto que vamos a modificar
    gasto = Gasto.objects.get(fecha=gasto_fecha)
    # Si es metodo POST hago lo mismo que el agregar
    if request.method == 'POST':

Proyecto2/App1/templates/App1/aboutMe.html
{% extends "App1/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}

    <!--Aquí va lo que cambia, y lo asociado a está vista :) -->
    {% if miFormulario.errors %} 
    <p style="color: red;">Estan mal los datos, revisar</p>
    {% endif %}    
     
    <font color="Olive" face="Comic Sans MS,arial">
    <h2 class="text-center">Hola mi nombre es Wentworth Pena Fonseca</h2>
    <p style="text-align:center">Soy Ingeniero Electronico, mi experiencia es en el area 
    del hardware y, las telecomunicaciones. Debido a la demanda mundial de 
    programadores y a las mejores oportunidades que se estan dando en ente campo, 
    he optado por ampliar mis conocimientos en el mundo de la programacion. Por 
    otra parte me gusta viajar todo el tiempo y con la ayuda de la progamacion lo 
    puedo hacer sin tener que abandonar o renunciar a mi trabajo.</p>              
    </font>          
  
{% endblock %}

Proyecto2/App1/templates/App1/editarPerfil.html
{% extends "App1/padre.html" %}
{% load static %}
{% block contenidoQueCambia %}


    <!--Aquí va lo que cambia, y lo asociado a está vista :) -->
    <font color="Olive" face="Comic Sans MS,arial">
    <h1>Editar Perfil De {{usuario}}</h1>
    </font>
    <form action="" method="POST">{% csrf_token %}
        <!-- Acá está la magia de Django-->
        <table>
            {{ miFormulario.as_table }}
        </table>
        <input type="submit", value="Enviar">
    </form>  

{% endblock %}

Proyecto2/App1/templates/App1/editarTrading.html
{% extends "App1/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}

    <!--Aquí va lo que cambia, y lo asociado a está vista :) -->
    <h1>Formulario - Editar Trading</h1>
    
    {% if miFormulario.errors %}

    <p style="color: red;"> Están mal los datos, revisar</p>

    {% endif %}

    <form action="" method="POST">{% csrf_token %}

        <!-- Acá está la magia de Django-->
        
        <table>

            {{ miFormulario.as_table }}

        </table>

        <input type="submit", value="Enviar">

    </form>

{% endblock %}

Proyecto2/App1/templates/App1/gasto_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <form method="post">{% csrf_token %}
        ¿Estas seguro de que deseas borrar el gasto "{{ object }}"?
        <input type="submit" value="Submit">
    </form>
</body>
</html>

Proyecto2/App1/templates/App1/gasto_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Gastos de Python</h1>
    <ul>
        {% for gasto in object_list %}
            <li>
                <p>Fecha: {{ gasto.fecha }}</p>
                <p>
                    <a href="{% url 'Detail' gasto.id %}">Ver</a>
                    <a href="{% url 'Edit' gasto.id %}">Editar</a>
                    <a href="{% url 'Delete' gasto.id %}">Borrar</a>
                </p>
            </li>
        {% endfor %}
    </ul>
    
</body>
</html>

Proyecto2/App1/templates/App1/ingresoFormulario.html
{% extends "App1/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}

    <!--Aquí va lo que cambia, y lo asociado a está vista :) -->
    {% if miFormulario.errors %} 
    <p style="color: red;">Estan mal los datos, revisar</p>
    {% endif %}

    <section class="py-1"> <!-- 5-->
        <div class="container my-1"> <!-- 5-->
            <div class="content-center">
                <div class="col-lg-6">  
                    <h2>Administra Tu Futuro</h2>
                    <p class="lead">Ahora ya puedes registrar el movimiento de tu dinero.</p>                   
                    <p class="lead"><strong>Ingresa la Informacion de Tus Ingresos.</strong></p>
                    <p class="lead"><strong>Digita la fecha en este formato, MM/DD/YYYY.</strong></p>
                </div>
            </div>
        </div>
    </section>

    <form action="" method="post">{% csrf_token %}
        <!--Aca esta la magia-->
        <table>
            {{ miFormulario.as_table }}
        </table>

        <input type="submit", value="Enviar">

    </form>

{% endblock %}

Proyecto2/App1/templates/App1/ingresos.html
{% extends "App1/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}

    <!--Aquí va lo que cambia, y lo asociado a está vista :) -->
    {% if miFormulario.errors %} 
    <p style="color: red;">Estan mal los datos, revisar</p>
    {% endif %}

    <section class="py-1"> <!-- 5-->
        <div class="container my-1"> <!-- 5-->
            <div class="content-center">
                <div class="col-lg-6">  
                    <font color="Olive" face="Comic Sans MS,arial">
                    <h2>Administra Tu Futuro</h2>                  
                    <p class="lead"><strong>Ingresa la Informacion de Tus Ingresos.</strong></p>
                    <p class="lead"><strong>Digita la fecha en este formato, MM/DD/YYYY.</strong></p>
                    </font>
                </div>
            </div>
        </div>
    </section>

    <form action="" method="post">{% csrf_token %}
        <!--Aca esta la magia-->
        <table>
            {{ miFormulario.as_table }}
        </table>

        <input type="submit", value="Enviar">

    </form>

    <br>
    <button type="button" class="btn btn-outline-info btn-sm"><a class="list-inline-item" href="{% url 'LeerIngresos' %}">Edita Tus Ingresos</a></button>
    <button type="button" class="btn btn-outline-info btn-sm"><a class="list-inline-item" href="{% url 'BusquedaIngreso' %}">Busca Tus Ingresos</a></button>

{% endblock %}

Proyecto2/App1/templates/App1/leerTradings.html
{% extends "App1/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
    <font color="Olive" face="Comic Sans MS,arial">
    <h1>Edita Tus Trading</h1>
    </font>
    <!--Aquí va lo que cambia, y lo asociado a está vista :) -->
    {% if miFormulario.errors %} 
    <p style="color: red;">Estan mal los datos, revisar</p>
    {% endif %}

    <body>
        {% for p in tradings %}
            <li>{{p}}</li>  
            <button type="button" class="btn btn-outline-info btn-sm"><a href="{% url 'EliminarTrading' p.fecha %}"> Eliminar</a></button>
            <button type="button" class="btn btn-outline-primary btn-sm"><a href="{% url 'EditarTrading' p.fecha %}">Editar</a></button>      
        {% endfor %}
        <br>
        <br>
        <!-- <a href="tradins">Agregar otro Trading</a> -->    
        <button type="button" class="btn btn-outline-primary btn-sm"><a href="{% url 'TradingFormulario' %}">Ingresa Otro Trading</a></button>
        
        
    </body>
        

{% endblock %}

Proyecto2/App1/templates/App1/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Protege Tu Futuro - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'App1/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                
                <a class="list-inline-item" href="{% url 'Inicio' %}">Inicio</a>
                <a class="navbar-brand" href="{% url 'Gasto' %}">Gastos</a>
                <a class="navbar-brand" href="{% url 'Ingreso' %}">Ingresos</a>
                <a class="navbar-brand" href="{% url 'Trading' %}">Trading</a>
                <a class="list-inline-item" href="{% url 'Login' %}">Login</a>
                <a class="list-inline-item" href="{% url 'Logout' %}">Logout</a>
                <a class="list-inline-item" href="{% url 'Register' %}">Registrate</a>             

                {% if request.user.is_authenticated %}
                    {% with avatares=request.user.avatar_set.all %}
                        {% if avatares %}
                             <img height="40px" src="{{avatares.0.imagen.url}}">
                        {% endif %}
                        <p class="text-muted small mb-4 mb-lg-0"> Hola, {{ request.user.username }} !!!</p>
                    {% endwith %}
                {% else %}
                    <a class="btn btn-primary" href="{% url 'Login' %}">INICIAR</a>
                {% endif %}
            </div>
        </nav>
        <!-- Header - set the background image for the header in the line below-->
        <header class="py-5 bg-image-full" style="background-image: url('https://source.unsplash.com/wfh8dDlNFOk/1600x900')">
            <div class="text-center my-5">   
                <font color="Olive" face="Comic Sans MS,arial">
                <h1>Protege Tu Futuro</h1>
                <h6>Esta aplicacion te permite tener registros de todos tus gastos,</h6>
                <h6>ingresos y de tus inversiones tambien.</h6>
                <h6>De esta manera cuidas tu futuro y el de los tuyos tambien.</h6>
                </font>
            </div>
        </header>
        <!-- Content section-->
        <section class="py-1"> <!-- 5-->
            <div class="container my-1"> <!-- 5-->
                <div class="content-center">
                    <div class="col-lg-6">
                    </div>
                </div>
            </div>
        </section>
        
        <!-- Esto es lo que va a cambiar-->

        {% block contenidoQueCambia %}

        {% endblock %}
        
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                <ul class="list-inline mb-2">
                    <font color="Olive" face="Comic Sans MS,arial">
                    <a class="list-inline-item" href="{% url 'EditarPerfil' %}">Edita tu Perfil</a>
                    <li class="list-inline-item">⋅</li> 
                    <a class="list-inline-item" href="{% url 'AgregarAvatar' %}">Agregar Avatar</a>
                    <li class="list-inline-item">⋅</li>
                    <a class="list-inline-item" href="{% url 'AboutMe' %}">About Me</a> 
                    <li class="list-inline-item">⋅</li>              
                    </font>
                </ul>
                <p class="text-muted small mb-4 mb-lg-0">&copy; Proyecto Python 2023 by Wentworth P. !!!.</p>
            </div>            
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

Proyecto2/App1/templates/App1/protected.html
<!DOCTYPE html>
<html>
<head>
    <title>My Template</title>
</head>
<body>
    <h1>{{ message }}</h1>
</body>
</html>